# TODO set volume directories
# TODO change ALL_CAPS environment variables in all locations

volumes:
  postgres:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/apple/miniflux/postgres

services:
  miniflux:
    image: miniflux/miniflux:latest
    # ports:
    #   - "80:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://miniflux:YOUR_PASSWORD@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      # - CREATE_ADMIN=1
      # - ADMIN_USERNAME=admin
      # - ADMIN_PASSWORD=test123
  db:
    image: postgres:18
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=YOUR_PASSWORD
      - POSTGRES_DB=miniflux
    volumes:
      - postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
