# TODO set volume directories
# TODO change ALL_CAPS environment variables in all locations
#       WORLD_NAME cannot have special characters or spaces, and must not start with a number

# Normally, I use external management to open up ports, but the definitions here are necessary.

volumes:
  LUANTI_SERVER:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Volumes/Treat/Containers/luanti-server/server

services:
  luanti_server:
    container_name: luanti_server
    image: lscr.io/linuxserver/luanti:5.16.1
    restart: always
    # networks:
    #   - default
    environment:
      - TZ=America/Denver
      # do not use --terminal or --server or --worldname
      - "CLI_ARGS=--gameid minetest --world /config/.minetest/worlds/WORLD_NAME"
      - PUID=1000
      - PGID=1000
    volumes:
      - LUANTI_SERVER:/config/.minetest
    ports:
      - "30000:30000/udp"
      - "127.0.0.1:30000:30000/tcp"
