# TODO set volume directories
# TODO change ALL_CAPS environment variables in all locations
#       (this is just WORLD_NAME here - it CANNOT have special characters or spaces, and must not start with a number)
# Normally, I use external management to open up ports, but the definitions here are necessary.

volumes:
  LUANTI_SERVER:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Volumes/Treat/Containers/luanti-server/server

name: luanti-server

services:
  luanti-server:
    container_name: luanti_server
    image: lscr.io/linuxserver/luanti:5.15.2
    restart: always
    # networks:
    #   - default
    environment:
      - TZ=America/Denver
      # do not use --terminal or --server or --worldname
      - "CLI_ARGS=--gameid minetest --world /config/.minetest/worlds/WORLD_NAME"
    volumes:
      - LUANTI_SERVER:/config/.minetest
    ports:
      - "30000:30000/udp"
      - "127.0.0.1:30000:30000/tcp"
